# Equiformer 网络配置 - 增强版等变图注意力Transformer (100M+ 参数)
name: equiformer

config:
  # 基础网络参数 - 大幅扩展到100M+
  max_atoms: 60              # 最大原子数
  hidden_channels: 768       # 隐藏通道数 (256→768，3倍扩展)
  num_layers: 12             # Equiformer块的层数 (8→12层)
  num_heads: 32              # 注意力头数 (16→32头)
  dropout_rate: 0.1          # Dropout率
  
  # 球谐函数和不可约表示
  lmax: 4                    # 球谐函数的最大阶数 (3→4阶)
  
  # 图构建参数
  max_radius: 15.0           # 图构建的最大半径 (Angstrom)
  num_basis: 512             # 径向基函数的数量 (256→512)
  
  # PXRD编码器参数
  pxrd_dim: 11501            # PXRD谱图维度
  pxrd_encoder:
    type: advanced           # 使用高级编码器 (CNN+Transformer+LSTM)
    hidden_dim: 1536         # 编码器隐藏维度 (512→1536，3倍扩展)
    use_cnn: true            # 使用多尺度CNN
    use_transformer: true    # 使用Transformer
    use_lstm: true           # 使用双向LSTM
    num_transformer_layers: 4  # Transformer层数 (2→4)
  
  # MatScholar嵌入路径
  matscholar_path: src/networks/matscholar.json
  
  # 优化参数（供训练时参考）
  optimizer:
    lr: 1e-4                 # 学习率
    weight_decay: 1e-5       # 权重衰减
    gradient_clip: 1.0       # 梯度裁剪